version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-planetstore
        environment:
            RABBITMQ_DEFAULT_USER: "planetstore"
            RABBITMQ_DEFAULT_PASS: "planetstore"
        ports:
            - "5672:5672"
            - "15672:15672"

    web-mvc:
        image: planetstore-web-mvc-ecommerce:latest
        container_name: planetstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/PSE.WebApp.MVC/Dockerfile
        restart: always         
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:50146
        depends_on:
            - api-catalog

    api-identification:
        image: planetstore-api-identification:latest
        container_name: planetstore-api-identification   
        build: 
            context: ../src
            dockerfile: ./services/PSE.Identification.API/Dockerfile
        restart: always  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:20840;http://+8215
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
    
    api-cart:
        image: planetstore-api-cart:latest
        container_name: planetstore-api-cart
        build: 
            context: ../src
            dockerfile: ./services/PSE.Cart.API/Dockerfile
        restart: always                 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:27444;http://+44202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identification     

    api-catalog:
        image: planetstore-api-catalog:latest
        container_name: planetstore-api-catalog
        build:
            context: ../src
            dockerfile: ./services/PSE.Catalog.API/Dockerfile
        restart: always 
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5011;http://+5010
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq

    api-clients:
        image: planetstore-api-clients:latest
        container_name: planetstore-api-clients    
        build: 
            context: ../src
            dockerfile: ./services/PSE.Clients.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:17530;http://+63540
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identification

    api-sales-bff:
        image: planetstore-api-sales-bff:latest
        container_name: planetstore-api-sales-bff
        build: 
            context: ../src
            dockerfile: ./ApiGateways/PSE.Sales.BFF/Dockerfile
        restart: always   
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:59188;http://+54173
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identification
            - api-cart
            - api-payment
            - api-order
    
    api-payment:
        image: planetstore-api-payment:latest
        container_name: planetstore-api-payment    
        build: 
            context: ../src
            dockerfile: ./services/PSE.Payment.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:60741;http://+10536
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identification
            - api-order
            
    api-order:
        image: planetstore-api-order:latest
        container_name: planetstore-api-order    
        build: 
            context: ../src
            dockerfile: ./services/PSE.Order.API/Dockerfile
        restart: always            
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:47207;http://+53089
            - ASPNETCORE_Kestrel__Certificates__Default__Password=planetstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/planetstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identification 

    planetstore-server-nginx:
        image: planetstore-server-nginx:latest
        container_name: planetstore-server-nginx   
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: always
        ports: 
            - "80:80"
            - "443:443" 
        depends_on:
            - web-mvc